[tool.poetry]
name = 'H1st-Util'
version = '0.0.0.dev17'
description = 'H1st Utilities'
authors = ['Aitomatic, Inc. <Engineering@Aitomatic.com>']
license = 'Apache-2.0'
readme = 'README.md'
homepage = 'https://GitHub.com/H1st-AI/H1st-Util'
repository = 'https://GitHub.com/H1st-AI/H1st-Util'
packages = [
  {include = 'h1st_util'}
]


[tool.poetry.dependencies]
Python = '>= 3.8, < 3.10'

# Data Processing
PyArrow = '^6.0.1'
PySpark = '^3.2.0'

# ML/DL
TensorFlow = '^2.7.0'

# AWS   # *** OFTEN CONFLICTS WITH OTHER DEPS ***
# AWSCLI = '*'
# Boto3 = '*'

# misc/other
PSUtil = '*' 


[build-system]
requires = [
  'Poetry-Core >= 1.0.7',
]
build-backend = 'poetry.core.masonry.api'
